hydra:
  run:
    dir: ./log/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dataset: food
  - trainer: default

inference:
  path: /SSL_NAS/peoples/suhyeon/food/food_data/
  name: train.parquet # train.parquet, val.parquet, test.parquet
  
mode:
  model: bertsum

train_checkpoint:
test_checkpoint: /home/food/people/suhyeon/extraction/bertsum/checkpoints/2025-06-13/10-39-38/epoch=4-step=3778.ckpt

model:
  base_checkpoint: bert-base-uncased # eng: bert-base-uncased, kor: klue/bert-base
  enc_num_layers: 2
  enc_intermediate_size: 2048
  enc_num_attention_heads: 8
  enc_dropout_prob: 0.1

max_seq_len: 512
batch_size: 16

engine:
  sum_size: 3
  pred_sum_size: 5
  n_block: 3
  model_checkpoint:
  freeze_base: False
  lr: 2e-3
  betas: [0.9, 0.999]
  weight_decay: 0.0
  num_warmup_steps: 10000
  save_result: True